# This is bogus, but needs to be here
language: c
compiler:
- gcc

# Install dependencies
sudo: true
dist: trusty
install:
 - sudo sed -i 's/trusty/xenial/' /etc/apt/sources.list # for new pandoc
 - sudo apt-get update -qq
 - sudo apt-get install -qq cadaver pandoc ca-certificates

script:
  - bin/convert

after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
     [ "$TRAVIS_REPO_SLUG" == "hroncok/MI-PYT" ] &&
     [ -n "$USERNAME" ] && [ -n "$PASSWORD" ]; then
        bin/create-netrc "$USERNAME" "$PASSWORD" && bin/deploy;
        rm ~/.netrc;
  fi

env:
  global:
  - secure: WPmhQpa14VDRZLjyJR8+b0p/c9PyWiIvZoZhQeaR/6k0b25DlQe52gkUK9DYTCoaFk4pl7C6dcWgsU7gVcj7kVDSbvhCROYAQFIuMuBcLndjU4Zl++WfAFRwu77Hc1LuqGJJRD8y1K773+1vo9urBt4OQXqZaBTlUMhBChUEEg05AWHUMmVjzwCbSFK+9qVLfRum2eY0HbfdWXmrVJ0nJj9Yvfe7cBv55rrMLrs16HDvhe5fI31Gs9fPI9ouar9GZ/TswAvc+qbHT/pxAZgsiVUyvD5dT1M+YI1XeurnPAPtEG/W56Jew0HxOoaHBqGQP1mAF6PaM3Zt6Ag97u/LnOTT+NX1Ddijt6ftILUfy/VRI/YnRbq4lHfy3Yl7eBblSbQ6WJ2csDWZF17gLNTG99RpbXOk7eaHFaUJcYhbSE2Iaq5BOK2GQ9MGa2xdn8VUxWp7hROXFcZhgAbU0aikpJTnHCn25I191uOyV5uROkU3lq+4My0EMlfioktBpi7gZmTOtRia1qIkHIlgAiG8N84ditvDDVMtxRJOmtHiyW3x3WJrLFtToyifu9t55H0lfE+PipKrRgnHLZb0ab0qp6We4KQGe6YR8T17b4Cw9iSU7SUyY1bqfrTwUkuu7OsnwckKh194phfhSPYEV6Tv/UAmSzbcffEFJroHKLWbJaI=
  - secure: HBZyNNnkUmlLlUJAGky7AS2qdmmwpzLI/BODBrAaIxIM7jBFpd4XeiorH/26EqiyVHGXZVKxaEpNLdMcztdWSXQmzOcOlxxtFUz9gBy6XE/NF2DNGFyHEJPkBw90RuK8NPI4yDainoKj9Sp7dNb0fvosTzwDk8BdMXBUQs18/JO62sOE0ExnRZpLl8osbyqqR43Rrh/d5nqK3PLRkt4KRWU3gQIjyQ0Nm0eRUIm5F7HuhvlEFJgti1FPk5ouJTQxyccVIkpIcEt+FjynisShL9n7M72WTOWLaWmEknOlPMZdD1xVgbSxekKZGRVpIaR4Rjl1uqN441ar+QUiuY67PVAzdeeco5ZLiwAewfZLlW3KYyzN23tQzOLy0cOZn2HeQxqd3WV4a1F1qH7FCNxpVxb4GpDxitsvMq79e1rL/3kQOHe28zfna/36KE+T5cHE5Hjj72szwiH0v7Rlzh/+LVZj+GEGSMOUfFi3ruCxStwhPtwcIjXhda3+Ksz0JkTRDGmbX2JFPkldKKPwCPaOSM/jREyZtW/THpnA4v0MJVGhCEObjCegShDWT51Pxh5MXPDW8Er5Y9gllYMsaLJNhddpt5DHZFeArE8xcYLQa8kkqm49cltf90HWAul0ihM0DBzYZnFf8daEQWI3WJ2Vlwc80nKgxKjrr0DxyToUBss=
